spring:
  application:
    name: feign-consumer
  profiles: feign-consumer
server:
  port: 8872


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
feign:
  hystrix:
    enabled: true
  

